version: '3'
services:
  django:
    build : .
    command : bash -c "gunicorn --reload --bind :8000 base.wsgi:application"
    #command : bash
    # command : tail -f /dev/null
    container_name: python__2
    hostname: kimchi
    ports:
      - 8000:8000
    # volumes: